### ISSUE TITLE
Prism support adobe after effects?

### ISSUE THREAD

**Issue by tws0002** [PrismPipeline/Prism#4]
Hi ,

I wonder Prism support adobe after effects? because i see now prism support adobe photoshop

Thanks 
Desmond

**Comment by RichardFrangenberg** [comment]
Hey Desmond,
As far as I know it's not possible to use the same method for After Effects, which I used for the Photoshop integration (the COM interface). But it looks like there are a few other workarounds to execute Python in After Effects, which would make a Prism integration possible.
However, since there are already a few compositing applications supported, there are other applications which have a higher priority for me at the moment (e.g. substance), but yes it would be possible in the future.

**Comment by tws0002** [comment]
thanks for the reply.
